//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchentsFirstProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class size
    {
        public int SizeID { get; set; }
        public Nullable<int> size1 { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Products1 Products1 { get; set; }
    }
}
