//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchentsFirstProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Shiping_Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Shiping_Address()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int AdderssId { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Apartment { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string Pincode { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<int> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Register Register { get; set; }
    }
}
