//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchentsFirstProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails1
    {
        public int OderDetaislId { get; set; }
        public int orderid { get; set; }
        public int productid { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Total { get; set; }
    
        public virtual OrderDetails1 OrderDetails11 { get; set; }
        public virtual OrderDetails1 OrderDetails12 { get; set; }
    }
}
