//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchentsFirstProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int orderId { get; set; }
        public string orderName { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> Productid { get; set; }
        public Nullable<int> Addressid { get; set; }
    
        public virtual User_Shiping_Address User_Shiping_Address { get; set; }
        public virtual Products1 Products1 { get; set; }
        public virtual Register Register { get; set; }
    }
}
